- en-US/L.xml
- en-US/O.xml
- en-US/S.xml
StarOffice is apparently still online, but I doubt it's got much of a userbase. I marked its entry as legacy, and added the modern equivalents (both of which suffer from the same CamelCaseSyndrome).
> legacyified StarOffice, added LibreOffice and OpenOffice

- css/style.css
This change makes the footer more flexible so that the links are not clobbered by the social media buttons when zooming in
> no more text clobbers when zooming

- en-US/S.xml
Updated file `s.xml` to highlight the prohibition on using "ssh" as a verb.
branch: `style-guide-issue-179`
> Updated SSH to highlight the prohibition on using as a verb-Issue #179

- en-US/F.xml
A super quick fix. This was wrong, so I removed the content for the entry and pointed to IBM.
> Fix #192 file extensions.

- en-US/Translation.xml
Somehow this patch got lost. It's been reviewed already so just readding
and publishing.
> Redo section on formatting lists.

- en-US/F.xml
Elaborated on the entry for FQDN at the same time.
@jmighion you won't be able to build the book but I modified the text thusly:
```
FQDN
A fully qualified domain name consists of a list of domain labels representing the hierarchy from the lowest 
relevant level in the DNS to the top-level domain (TLD). The domain labels are concatenated using the full 
stop (.) character (dot or period) as a separator between labels. ⁠[8]
For example, www.redhat.com is a fully qualified domain name, where “www” is the host, “redhat” is the 
second-level domain, and “com” is the top-level domain.
A FQDN always starts with a host name and continues all the way up to the top-level domain name; 
consequently “www.parc.xerox.com” is also a FQDN. 
```
[8] is a link to a footnote that references Wikipedia, …
> Address #207 missing hyphenation.

- en-US/Design.xml
Includes more info and examples from `info libc` and further references.
> Update section on option and argument terminology.

- en-US/Book_Info.xml
- en-US/Design.xml
This covers the initial aspect of this issue, which allows for the use
or not of line continuation chars and PS2 prompts. Probably still need
to sync with info in the DocBook Guide.
> #216 continuation prompts

- en-US/B.xml
- en-US/L.xml
Remove reference to IBM guide because it conflicts with our own.
Note that this version does not build because of an entity issue, but
that's been fixed as part of a separate commit.
> Addresses #224 Update entry for life cycle.

- en-US/Design.xml
Would very much appreciate review by a techie person, both because of the nature of the material and also because it's a public guide and this commit touches on how we configure our courses to some degree.
> Addresses #222 Recommendations for using sudo.

- en-US/Design.xml
Add subsection on phraseology for changing to the root user.
> Fixes #235

- en-US/Design.xml
uinames link no longer works.
We have two other options so I just removed this one. Subsection now appears as follows:
> Fixes #280

- en-US/Design.xml
> #306 Added guidance about pronouncing file or directory names that begin with special characters.

- index.html
* Updated copyright year
* Updated versions on links to style guides
* Removed statement about providing DocBook guidance
> Fixes #409 and other required repairs.

- en-US/Book_Design.xml
- en-US/Design.xml
- en-US/Grammar.xml
- en-US/Language.xml
- en-US/Punctuation.xml
- en-US/Translation.xml
Addresses these issues:
#24 
#79 
#364 
#369 
#373 
#404 
#406
> Applied various fixes for 6.0

- en-US/Book_Info.xml
- en-US/Grammar.xml
- en-US/Language.xml
- en-US/Translation.xml
Please review these enhancements for the upcoming October Release 6.0 of the style guide, to add previously missing guidance from the snippets.
> Applied first batch of enhancements for 6.0

- en-US/Design.xml
A small subsection on when and when not to use captions and callouts.
> Addresses #424 Add info on using captions.

- en-US/A.xml
- en-US/Author_Group.xml
- en-US/B.xml
- en-US/Book_Design.xml
- en-US/Cross_references.xml
- en-US/Design.xml
- Working on #450.
- Run Vale over Design.xml.
- No major changes, just a few word swaps.
- See also https://github.com/RedHatTraining/vale-styles/issues/175
> Vale check of Style Guide Part 1

- en-US/Language.xml
I added information on how to use inclusive names when creating a default branch for a GitHub’s repository.
As a Black woman who frequents the open source community, seeing “master” as the central branch illicits images of slavery. This causes me and others black open source contributors to feel that our contributions are inferior, thus, causing us to lose interest in contributing to the project.
Creates a more inclusive environment.
- Fixes issue #489
> feat: Add advice on naming the default branch in an inclusive way.

- en-US/Design.xml
@daobrien @sffrench Please review the "Writing Effective Titles" section, which I've updated to reflect the recently changed guidance that Pat announced.
> Updated section about writing titles

- en-US/Design.xml
Updated to reflect the latest guidance on continuation prompts as communicated by Pat. A previous choice of three possible options is now replaced with just a single approach.
@daobrien @sffrench Please review.
> Updated guidance on continuation prompts

- en-US/Design.xml
- en-US/Grammar.xml
- en-US/Punctuation.xml
The style guide needs information about effectively using possessives.
This PR adds a new section to the Grammar.xml file called "Possessives". It provides guidelines on when to use possessives and when to avoid using them. 
Closes #517 
I'm open to feedback on how to change the formatting.
> Adding information about posessives

- en-US/0-9.xml
- en-US/A.xml
- en-US/I.xml
- en-US/XYZ.xml
Implementing the formal documented guidance for these related terms, as approved by Word Nerds.
> Add 64-bit architecture guidance

- en-US/Design.xml
I have added `ulink` tag to a URL footnote.
Changing color for a non-URL footnote requires css update.
We can do this by updating configuration file for site building tool.
**Before**
LightMode
DarkMode
**After**
LightMode
DarkMode
> Footnote update

- en-US/Book_Design.xml
- en-US/C.xml
- en-US/Design.xml
- en-US/G.xml
- en-US/Grammar.xml
- en-US/Language.xml
- en-US/S.xml
- en-US/T.xml
- en-US/Translation.xml
- en-US/U.xml
This PR implements many suggestions from @jdandrea in this document: 
https://docs.google.com/spreadsheets/d/1K3dlBNAb7Q6ZOSeCtKfxSDKfYWnYzWlbpups3P1JOMk
> Implement suggestions from Ashley D'Andrea

- en-US/Design.xml
Remove the "yes" and "no" options for `become` in Ansible Playbooks and YAML files, preferring only the "true" and "false" options for Booleans.  This is the recommended practice based on *ansible-lint* rules and Ansible BU input.
> Remove yes/no as values for Ansible 'become'
