StyleGuides/WritingStyleGuide

en-US/Translation.xml
Taking our own medicine just a bit to help this text be more translatable itself...
=> Reduce passive voice and wordiness

en-US/H.xml, en-US/T.xml
Discussed and agreed to by Word Nerds group.
=> Add entries for tooltip and hover help.

en-US/G.xml
Also fixed a couple of trivial wording issues.
=> Add entry for GbE #57

en-US/O.xml
=> open source way, issue #91

en-US/Design.xml
Added extended list from internal discussions.
=> Address #87 Revise section of how to use user names.

en-US/O.xml, en-US/P.xml
=> Bz 1172239

en-US/Design.xml
Seth, please review and compare with source doc to see if I've missed anything.
I've tried to genericise a bit to make it suitable for a wider audience.
=> Address issue #125 re user names

en-US/Design.xml
Update usage instructions for product names, abbreviations, and version
numbers.
=> Addresses #158

en-US/M.xml
Also fixed entry for "mutex."
Here I stand, hat in hand, hoping somebody will take a minute to ack, just so that I'm not the only person adding to the style guide :)
You won't be able to build it "properly" unless you have the correct brand and publican installed, but just have a look at the xml if you have a few mins.
=> Fixing #163 "add multicloud"

en-US/Translation.xml
This is mainly for Nicole, but @notklaatu if you care to chime in that would be great.
=> #159 "Elaborate section on lists."

en-US/Design.xml
Updated Design.xml with content from #168 
Updates start at about line #350
=> Address #168 Admin user clarity.

en-US/U.xml
Simple fix. Add content for UUID and link back to entry for UID.
=> Address #85 for UUID.

en-US/T.xml
Added entry for telco and telecommunications provider.
Addresses #177
=> Add entry for telco and telecommunications provider. Addresses #177

en-US/Grammar.xml, en-US/O.xml, en-US/R.xml
Added entry for Once and changed incorrect use of the word once.
Addresses #172
=> Add entry for Once. Addresses #172

en-US/Design.xml, en-US/Slang.xml
Add information on verbiage for recommendations to address Issue #173.
=> Addresses Style Guide Issue #173

en-US/Design.xml
Updated URL for titlecase web site
Fixed - https://github.com/StyleGuides/WritingStyleGuide/issues/200
=> Updated URL for titlecase web site

en-US/Design.xml, en-US/N.xml
Added "navigate to" entry and "navigating through multiple GUI options"
Addresses #188
=> Added "navigate to" entry and navigating through multiple GUI options

index.html
- update url and link text to v2 and v3
- remove point release references
=> Splash Page Updates

en-US/A.xml, en-US/Design.xml, en-US/I.xml, en-US/N.xml, en-US/P.xml, en-US/Translation.xml, index.html
There were a few nagging issues that I wanted to get into master sooner rather than later, primarily the section about lists, which got missed. There's a commit about parsing the Usage Dictionary which is incomplete but of little consequence atm because a) it doesn't impact the guide content, and b) will likely go through a lot more devel in parallel with `Vale` and rules related to `pre-commit`.
afaict everything else is just wording patches, clean-up, and similar.
@niklucas and @nmuller66 can you both have a bit of a look and Nikki can you publish? I'll be on PTO for the next week. Thanks a bunch.
=> Merge dev to master for point release

en-US/M.xml
Added entry for "macOS"
[Issue #68](https://github.com/StyleGuides/WritingStyleGuide/issues/68#issuecomment-702484041)
=> Added entry for "macOS"

en-US/E.xml
Added EOL to the Usage Dictionary. Issue [#48](https://github.com/StyleGuides/WritingStyleGuide/issues/48)
=> Adding EOL to Usage Dictionary

en-US/B.xml
Updated entry for "backward compatible" 
Added entry for "backwards".
Fixes - https://github.com/StyleGuides/WritingStyleGuide/issues/157
=> Updated entry for "backward compatible"

en-US/B.xml
Update example text and add link to Documenting the UI.
Super trivial update. Note that this version won't build because of entity issue. Fixed in another commit.
=> Addresses #219 Update entry for "Button."

en-US/Design.xml
=> Fixes #247

en-US/Language.xml
Removed several slang terms that would probably never get used.
=> Closes #258

en-US/Design.xml, en-US/E.xml, en-US/F.xml, en-US/H.xml, en-US/U.xml
s/host name/hostname/ and s/user name/username/ based on revised
guidance in IBM.
=> Fixes #262

index.html
Re-added link to latest DocBook Guide until all content is migrated.
Also added icons for each link.
=> Fixes #274

index.html
Add entry to allow for previous and current versions of guide.
=> Fixes #277

en-US/C.xml, en-US/U.xml
Remove entry for "check box" (no longer correct and covered in IBM) and
update to other references that use "check box".
=> Fixes #294

en-US/Design.xml
=> #291 Diagram labels as sentence case only.

en-US/Design.xml
=> 337 Add guidance about referring to UI elements and other publication titles

en-US/V.xml
Basically copy/paste from corp guide.
=> Closes #78 Update entry for "virtualized".
